function jornada(){var S='bootstrap',T='begin',U='gwt.codesvr.jornada=',V='gwt.codesvr=',W='jornada',X='startup',Y='DUMMY',Z=0,$=1,_='iframe',ab='javascript:""',bb='position:absolute; width:0; height:0; border:none; left: -1000px;',cb=' top: -1000px;',db='CSS1Compat',eb='<!doctype html>',fb='',gb='<html><head><\/head><body><\/body><\/html>',hb='undefined',ib='DOMContentLoaded',jb=50,kb='Chrome',lb='eval("',mb='");',nb='script',ob='javascript',pb='moduleStartup',qb='moduleRequested',rb='Failed to load ',sb='head',tb='meta',ub='name',vb='jornada::',wb='::',xb='gwt:property',yb='content',zb='=',Ab='gwt:onPropertyErrorFn',Bb='Bad handler "',Cb='" for "gwt:onPropertyErrorFn"',Db='gwt:onLoadErrorFn',Eb='" for "gwt:onLoadErrorFn"',Fb='#',Gb='?',Hb='/',Ib='img',Jb='clear.cache.gif',Kb='baseUrl',Lb='jornada.nocache.js',Mb='base',Nb='//',Ob='locale',Pb='default',Qb='locale=',Rb=7,Sb='&',Tb='_',Ub='__gwt_Locale',Vb='Unexpected exception in locale detection, using default: ',Wb=2,Xb='user.agent',Yb='webkit',Zb='safari',$b='msie',_b=10,ac=11,bc='ie10',cc=9,dc='ie9',ec=8,fc='ie8',gc='gecko',hc='gecko1_8',ic=3,jc=4,kc='selectingPermutation',lc='jornada.devmode.js',mc='1CE2B8061F3F33E6005D2747DFE1C9C5',nc='en',oc='3416BBFE41B8AF302A86061B3C5D3AC4',pc='34325DB911CEE7182713BFF940AC6AEF',qc='pt_BR',rc='65E72DE89A6E39612888441E09E1EA4D',sc='6916E7020D38F8016CE89A42740DDEDE',tc='748FE3641FFEABD90232BAB110874914',uc='858DDEA2AD6D154FF1EC933AC595DD66',vc='943C4714E051E0A9170476E47FD4B66B',wc='A5E024B8A61694D52C1930AAD54611A9',xc='A5E8B6BA1FEB23258A63E233CE52D9EC',yc='A8CBC7085E920E0645F23452B9094978',zc='D3C4769E038E45A57278545F84AB5B4F',Ac='D8B6C0085A079D9D6A35233E05C97338',Bc='E9471FE16916F25F41CEE12800D13FBF',Cc='F2E7699306BA0DB2FA425CE80E3D226A',Dc=':',Ec='.cache.js',Fc='link',Gc='rel',Hc='stylesheet',Ic='href',Jc='loadExternalRefs',Kc='gwt/clean/clean.css',Lc='end',Mc='http:',Nc='file:',Oc='_gwt_dummy_',Pc='__gwtDevModeHook:jornada',Qc='Ignoring non-whitelisted Dev Mode URL: ',Rc=':moduleBase';var s=window;var t=document;v(S,T);function u(){var a=s.location.search;return a.indexOf(U)!=-1||a.indexOf(V)!=-1}
function v(a,b){if(s.__gwtStatsEvent){s.__gwtStatsEvent({moduleName:W,sessionId:s.__gwtStatsSessionId,subSystem:X,evtGroup:a,millis:(new Date).getTime(),type:b})}}
jornada.__sendStats=v;jornada.__moduleName=W;jornada.__errFn=null;jornada.__moduleBase=Y;jornada.__softPermutationId=Z;jornada.__computePropValue=null;jornada.__getPropMap=null;jornada.__installRunAsyncCode=function(){};jornada.__gwtStartLoadingFragment=function(){return null};jornada.__gwt_isKnownPropertyValue=function(){return false};jornada.__gwt_getMetaProperty=function(){return null};var w=null;var A=s.__gwt_activeModules=s.__gwt_activeModules||{};A[W]={moduleName:W};jornada.__moduleStartupDone=function(e){var f=A[W].bindings;A[W].bindings=function(){var a=f?f():{};var b=e[jornada.__softPermutationId];for(var c=Z;c<b.length;c++){var d=b[c];a[d[Z]]=d[$]}return a}};var B;function C(){D();return B}
function D(){if(B){return}var a=t.createElement(_);a.src=ab;a.id=W;a.style.cssText=bb+cb;a.tabIndex=-1;t.body.appendChild(a);B=a.contentDocument;if(!B){B=a.contentWindow.document}B.open();var b=document.compatMode==db?eb:fb;B.write(b+gb);B.close()}
function F(k){function l(a){function b(){if(typeof t.readyState==hb){return typeof t.body!=hb&&t.body!=null}return /loaded|complete/.test(t.readyState)}
var c=b();if(c){a();return}function d(){if(!c){c=true;a();if(t.removeEventListener){t.removeEventListener(ib,d,false)}if(e){clearInterval(e)}}}
if(t.addEventListener){t.addEventListener(ib,d,false)}var e=setInterval(function(){if(b()){d()}},jb)}
function m(c){function d(a,b){a.removeChild(b)}
var e=C();var f=e.body;var g;if(navigator.userAgent.indexOf(kb)>-1&&window.JSON){var h=e.createDocumentFragment();h.appendChild(e.createTextNode(lb));for(var i=Z;i<c.length;i++){var j=window.JSON.stringify(c[i]);h.appendChild(e.createTextNode(j.substring($,j.length-$)))}h.appendChild(e.createTextNode(mb));g=e.createElement(nb);g.language=ob;g.appendChild(h);f.appendChild(g);d(f,g)}else{for(var i=Z;i<c.length;i++){g=e.createElement(nb);g.language=ob;g.text=c[i];f.appendChild(g);d(f,g)}}}
jornada.onScriptDownloaded=function(a){l(function(){m(a)})};v(pb,qb);var n=t.createElement(nb);n.src=k;if(jornada.__errFn){n.onerror=function(){jornada.__errFn(W,new Error(rb+code))}}t.getElementsByTagName(sb)[Z].appendChild(n)}
jornada.__startLoadingFragment=function(a){return I(a)};jornada.__installRunAsyncCode=function(a){var b=C();var c=b.body;var d=b.createElement(nb);d.language=ob;d.text=a;c.appendChild(d);c.removeChild(d)};function G(){var c={};var d;var e;var f=t.getElementsByTagName(tb);for(var g=Z,h=f.length;g<h;++g){var i=f[g],j=i.getAttribute(ub),k;if(j){j=j.replace(vb,fb);if(j.indexOf(wb)>=Z){continue}if(j==xb){k=i.getAttribute(yb);if(k){var l,m=k.indexOf(zb);if(m>=Z){j=k.substring(Z,m);l=k.substring(m+$)}else{j=k;l=fb}c[j]=l}}else if(j==Ab){k=i.getAttribute(yb);if(k){try{d=eval(k)}catch(a){alert(Bb+k+Cb)}}}else if(j==Db){k=i.getAttribute(yb);if(k){try{e=eval(k)}catch(a){alert(Bb+k+Eb)}}}}}__gwt_getMetaProperty=function(a){var b=c[a];return b==null?null:b};w=d;jornada.__errFn=e}
function H(){function e(a){var b=a.lastIndexOf(Fb);if(b==-1){b=a.length}var c=a.indexOf(Gb);if(c==-1){c=a.length}var d=a.lastIndexOf(Hb,Math.min(c,b));return d>=Z?a.substring(Z,d+$):fb}
function f(a){if(a.match(/^\w+:\/\//)){}else{var b=t.createElement(Ib);b.src=a+Jb;a=e(b.src)}return a}
function g(){var a=__gwt_getMetaProperty(Kb);if(a!=null){return a}return fb}
function h(){var a=t.getElementsByTagName(nb);for(var b=Z;b<a.length;++b){if(a[b].src.indexOf(Lb)!=-1){return e(a[b].src)}}return fb}
function i(){var a=t.getElementsByTagName(Mb);if(a.length>Z){return a[a.length-$].href}return fb}
function j(){var a=t.location;return a.href==a.protocol+Nb+a.host+a.pathname+a.search+a.hash}
var k=g();if(k==fb){k=h()}if(k==fb){k=i()}if(k==fb&&j()){k=e(t.location.href)}k=f(k);return k}
function I(a){if(a.match(/^\//)){return a}if(a.match(/^[a-zA-Z]+:\/\//)){return a}return jornada.__moduleBase+a}
function J(){var k=[];var l=Z;function m(a,b){var c=k;for(var d=Z,e=a.length-$;d<e;++d){c=c[a[d]]||(c[a[d]]=[])}c[a[e]]=b}
var n=[];var o=[];function p(a){var b=o[a](),c=n[a];if(b in c){return b}var d=[];for(var e in c){d[c[e]]=e}if(w){w(a,d,b)}throw null}
o[Ob]=function(){var b=null;var c=Pb;try{if(!b){var d=location.search;var e=d.indexOf(Qb);if(e>=Z){var f=d.substring(e+Rb);var g=d.indexOf(Sb,e);if(g<Z){g=d.length}b=d.substring(e+Rb,g)}}if(!b){b=__gwt_getMetaProperty(Ob)}if(!b){var h=navigator.browserLanguage?navigator.browserLanguage:navigator.language;if(h){var i=h.split(/[-_]/);if(i.length>$){i[$]=i[$].toUpperCase()}b=i.join(Tb)}}if(!b){b=s[Ub]}if(b){c=b}while(b&&!__gwt_isKnownPropertyValue(Ob,b)){var j=b.lastIndexOf(Tb);if(j<Z){b=null;break}b=b.substring(Z,j)}}catch(a){alert(Vb+a)}s[Ub]=c;return b||Pb};n[Ob]={'default':Z,en:$,pt_BR:Wb};o[Xb]=function(){var a=navigator.userAgent.toLowerCase();var b=t.documentMode;if(function(){return a.indexOf(Yb)!=-1}())return Zb;if(function(){return a.indexOf($b)!=-1&&(b>=_b&&b<ac)}())return bc;if(function(){return a.indexOf($b)!=-1&&(b>=cc&&b<ac)}())return dc;if(function(){return a.indexOf($b)!=-1&&(b>=ec&&b<ac)}())return fc;if(function(){return a.indexOf(gc)!=-1||b>=ac}())return hc;return fb};n[Xb]={gecko1_8:Z,ie10:$,ie8:Wb,ie9:ic,safari:jc};__gwt_isKnownPropertyValue=function(a,b){return b in n[a]};jornada.__getPropMap=function(){var a={};for(var b in n){if(n.hasOwnProperty(b)){a[b]=p(b)}}return a};jornada.__computePropValue=p;s.__gwt_activeModules[W].bindings=jornada.__getPropMap;v(S,kc);if(u()){return I(lc)}var q;try{m([Pb,bc],mc);m([nc,Zb],oc);m([nc,dc],pc);m([qc,hc],rc);m([Pb,Zb],sc);m([nc,bc],tc);m([qc,Zb],uc);m([nc,fc],vc);m([Pb,fc],wc);m([Pb,hc],xc);m([qc,fc],yc);m([qc,dc],zc);m([Pb,dc],Ac);m([qc,bc],Bc);m([nc,hc],Cc);q=k[p(Ob)][p(Xb)];var r=q.indexOf(Dc);if(r!=-1){l=parseInt(q.substring(r+$),_b);q=q.substring(Z,r)}}catch(a){}jornada.__softPermutationId=l;return I(q+Ec)}
function K(){if(!s.__gwt_stylesLoaded){s.__gwt_stylesLoaded={}}function c(a){if(!__gwt_stylesLoaded[a]){var b=t.createElement(Fc);b.setAttribute(Gc,Hc);b.setAttribute(Ic,I(a));t.getElementsByTagName(sb)[Z].appendChild(b);__gwt_stylesLoaded[a]=true}}
v(Jc,T);c(Kc);v(Jc,Lc)}
G();jornada.__moduleBase=H();A[W].moduleBase=jornada.__moduleBase;var L=J();if(s){var M=!!(s.location.protocol==Mc||s.location.protocol==Nc);s.__gwt_activeModules[W].canRedirect=M;function N(){var b=Oc;try{s.sessionStorage.setItem(b,b);s.sessionStorage.removeItem(b);return true}catch(a){return false}}
if(M&&N()){var O=Pc;var P=s.sessionStorage[O];if(!/^http:\/\/(localhost|127\.0\.0\.1)(:\d+)?\/.*$/.test(P)){if(P&&(window.console&&console.log)){console.log(Qc+P)}P=fb}if(P&&!s[O]){s[O]=true;s[O+Rc]=H();var Q=t.createElement(nb);Q.src=P;var R=t.getElementsByTagName(sb)[Z];R.insertBefore(Q,R.firstElementChild||R.children[Z]);return false}}}K();v(S,Lc);F(L);return true}
jornada.succeeded=jornada();