package com.jornada.client.classes.listBoxes.suggestbox;

import com.google.gwt.user.client.ui.MultiWordSuggestOracle;

public class MpSuggestOracleCidadesSP extends MultiWordSuggestOracle{
    
    public MpSuggestOracleCidadesSP(){
        
        super.add("Adamantina");
        super.add("Adolfo");
        super.add("Aguai");
        super.add("Aguas da Prata");
        super.add("Aguas de Lindoia");
        super.add("Aguas de Santa Barbara");
        super.add("Aguas de Sao Pedro");
        super.add("Agudos");
        super.add("Alambari");
        super.add("Alfredo Marcondes");
        super.add("Altair");
        super.add("Altinopolis");
        super.add("Alto Alegre");
        super.add("Aluminio");
        super.add("Alvares Florence");
        super.add("Alvares Machado");
        super.add("Alvaro de Carvalho");
        super.add("Alvinlandia");
        super.add("Americana");
        super.add("Americo Brasiliense");
        super.add("Americo de Campos");
        super.add("Amparo");
        super.add("Analandia");
        super.add("Andradina");
        super.add("Angatuba");
        super.add("Anhembi");
        super.add("Anhumas");
        super.add("Aparecida d'Oeste");
        super.add("Aparecida");
        super.add("Apiai");
        super.add("Aracariguama");
        super.add("Aracatuba");
        super.add("Aracoiaba da Serra");
        super.add("Aramina");
        super.add("Arandu");
        super.add("Arapei");
        super.add("Araraquara");
        super.add("Araras");
        super.add("Arco-Iris");
        super.add("Arealva");
        super.add("Areias");
        super.add("Areiopolis");
        super.add("Ariranha");
        super.add("Artur Nogueira");
        super.add("Aruja");
        super.add("Aspasia");
        super.add("Assis");
        super.add("Atibaia");
        super.add("Auriflama");
        super.add("Avai");
        super.add("Avanhandava");
        super.add("Avare");
        super.add("Bady Bassitt");
        super.add("Balbinos");
        super.add("Balsamo");
        super.add("Bananal");
        super.add("Barao de Antonina");
        super.add("Barbosa");
        super.add("Bariri");
        super.add("Barra Bonita");
        super.add("Barra do Chapeu");
        super.add("Barra do Turvo");
        super.add("Barretos");
        super.add("Barrinha");
        super.add("Barueri");
        super.add("Bastos");
        super.add("Batatais");
        super.add("Bauru");
        super.add("Bebedouro");
        super.add("Bento de Abreu");
        super.add("Bernardino de Campos");
        super.add("Bertioga");
        super.add("Bilac");
        super.add("Birigui");
        super.add("Biritiba-Mirim");
        super.add("Boa Esperanca do Sul");
        super.add("Bocaina");
        super.add("Bofete");
        super.add("Boituva");
        super.add("Bom Jesus dos Perdoes");
        super.add("Bom Sucesso de Itarare");
        super.add("Bora");
        super.add("Boraceia");
        super.add("Borborema");
        super.add("Borebi");
        super.add("Botucatu");
        super.add("Braganca Paulista");
        super.add("Brauna");
        super.add("Brejo Alegre");
        super.add("Brodosqui");
        super.add("Brotas");
        super.add("Buri");
        super.add("Buritama");
        super.add("Buritizal");
        super.add("Cabralia Paulista");
        super.add("Cabreuva");
        super.add("Cacapava");
        super.add("Cachoeira Paulista");
        super.add("Caconde");
        super.add("Cafelandia");
        super.add("Caiabu");
        super.add("Caieiras");
        super.add("Caiua");
        super.add("Cajamar");
        super.add("Cajati");
        super.add("Cajobi");
        super.add("Cajuru");
        super.add("Campina do Monte Alegre");
        super.add("Campinas");
        super.add("Campo Limpo Paulista");
        super.add("Campos Novos Paulista");
        super.add("Campos do Jordao");
        super.add("Cananeia");
        super.add("Canas");
        super.add("Candido Mota");
        super.add("Candido Rodrigues");
        super.add("Canitar");
        super.add("Capao Bonito");
        super.add("Capela do Alto");
        super.add("Capivari");
        super.add("Caraguatatuba");
        super.add("Carapicuiba");
        super.add("Cardoso");
        super.add("Casa Branca");
        super.add("Cassia dos Coqueiros");
        super.add("Castilho");
        super.add("Catanduva");
        super.add("Catigua");
        super.add("Cedral");
        super.add("Cerqueira Cesar");
        super.add("Cerquilho");
        super.add("Cesario Lange");
        super.add("Charqueada");
        super.add("Chavantes");
        super.add("Clementina");
        super.add("Colina");
        super.add("Colombia");
        super.add("Conchal");
        super.add("Conchas");
        super.add("Cordeiropolis");
        super.add("Coroados");
        super.add("Coronel Macedo");
        super.add("Corumbatai");
        super.add("Cosmopolis");
        super.add("Cosmorama");
        super.add("Cotia");
        super.add("Cravinhos");
        super.add("Cristais Paulista");
        super.add("Cruzalia");
        super.add("Cruzeiro");
        super.add("Cubatao");
        super.add("Cunha");
        super.add("Descalvado");
        super.add("Diadema");
        super.add("Dirce Reis");
        super.add("Divinolandia");
        super.add("Dobrada");
        super.add("Dois Corregos");
        super.add("Dolcinopolis");
        super.add("Dourado");
        super.add("Dracena");
        super.add("Duartina");
        super.add("Dumont");
        super.add("Echapora");
        super.add("Eldorado");
        super.add("Elias Fausto");
        super.add("Elisiario");
        super.add("Embauba");
        super.add("Embu");
        super.add("Embu-Guacu");
        super.add("Emilianopolis");
        super.add("Engenheiro Coelho");
        super.add("Espirito Santo do Pinhal");
        super.add("Espirito Santo do Turvo");
        super.add("Estiva Gerbi");
        super.add("Estrela d'Oeste");
        super.add("Estrela do Norte");
        super.add("Euclides da Cunha Paulista");
        super.add("Fartura");
        super.add("Fernando Prestes");
        super.add("Fernandopolis");
        super.add("Fernao");
        super.add("Ferraz de Vasconcelos");
        super.add("Flora Rica");
        super.add("Floreal");
        super.add("Florida Paulista");
        super.add("Florinia");
        super.add("Franca");
        super.add("Francisco Morato");
        super.add("Franco da Rocha");
        super.add("Gabriel Monteiro");
        super.add("Galia");
        super.add("Garca");
        super.add("Gastao Vidigal");
        super.add("Gaviao Peixoto");
        super.add("General Salgado");
        super.add("Getulina");
        super.add("Glicerio");
        super.add("Guaicara");
        super.add("Guaimbe");
        super.add("Guaira");
        super.add("Guapiacu");
        super.add("Guapiara");
        super.add("Guara");
        super.add("Guaracai");
        super.add("Guaraci");
        super.add("Guarani d'Oeste");
        super.add("Guaranta");
        super.add("Guararapes");
        super.add("Guararema");
        super.add("Guaratingueta");
        super.add("Guarei");
        super.add("Guariba");
        super.add("Guaruja");
        super.add("Guarulhos");
        super.add("Guatapara");
        super.add("Guzolandia");
        super.add("Herculandia");
        super.add("Holambra");
        super.add("Hortolandia");
        super.add("Iacanga");
        super.add("Iacri");
        super.add("Iaras");
        super.add("Ibate");
        super.add("Ibira");
        super.add("Ibirarema");
        super.add("Ibitinga");
        super.add("Ibiuna");
        super.add("Icem");
        super.add("Iepe");
        super.add("Igaracu do Tiete");
        super.add("Igarapava");
        super.add("Igarata");
        super.add("Iguape");
        super.add("Ilha Comprida");
        super.add("Ilha Solteira");
        super.add("Ilhabela");
        super.add("Indaiatuba");
        super.add("Indiana");
        super.add("Indiapora");
        super.add("Inubia Paulista");
        super.add("Ipaucu");
        super.add("Ipero");
        super.add("Ipeuna");
        super.add("Ipigua");
        super.add("Iporanga");
        super.add("Ipua");
        super.add("Iracemapolis");
        super.add("Irapua");
        super.add("Irapuru");
        super.add("Itabera");
        super.add("Itai");
        super.add("Itajobi");
        super.add("Itaju");
        super.add("Itanhaem");
        super.add("Itaoca");
        super.add("Itapecerica da Serra");
        super.add("Itapetininga");
        super.add("Itapeva");
        super.add("Itapevi");
        super.add("Itapira");
        super.add("Itapirapua Paulista");
        super.add("Itapolis");
        super.add("Itaporanga");
        super.add("Itapui");
        super.add("Itapura");
        super.add("Itaquaquecetuba");
        super.add("Itarare");
        super.add("Itariri");
        super.add("Itatiba");
        super.add("Itatinga");
        super.add("Itirapina");
        super.add("Itirapua");
        super.add("Itobi");
        super.add("Itu");
        super.add("Itupeva");
        super.add("Ituverava");
        super.add("Jaborandi");
        super.add("Jaboticabal");
        super.add("Jacarei");
        super.add("Jaci");
        super.add("Jacupiranga");
        super.add("Jaguariuna");
        super.add("Jales");
        super.add("Jambeiro");
        super.add("Jandira");
        super.add("Jardinopolis");
        super.add("Jarinu");
        super.add("Jau");
        super.add("Jeriquara");
        super.add("Joanopolis");
        super.add("Joao Ramalho");
        super.add("Jose Bonifacio");
        super.add("Julio Mesquita");
        super.add("Jumirim");
        super.add("Jundiai");
        super.add("Junqueiropolis");
        super.add("Juquia");
        super.add("Juquitiba");
        super.add("Lagoinha");
        super.add("Laranjal Paulista");
        super.add("Lavinia");
        super.add("Lavrinhas");
        super.add("Leme");
        super.add("Lencois Paulista");
        super.add("Limeira");
        super.add("Lindoia");
        super.add("Lins");
        super.add("Lorena");
        super.add("Lourdes");
        super.add("Louveira");
        super.add("Lucelia");
        super.add("Lucianopolis");
        super.add("Luis Antonio");
        super.add("Luiziania");
        super.add("Lupercio");
        super.add("Lutecia");
        super.add("Macatuba");
        super.add("Macaubal");
        super.add("Macedonia");
        super.add("Magda");
        super.add("Mairinque");
        super.add("Mairipora");
        super.add("Manduri");
        super.add("Maraba Paulista");
        super.add("Maracai");
        super.add("Marapoama");
        super.add("Mariapolis");
        super.add("Marilia");
        super.add("Marinopolis");
        super.add("Martinopolis");
        super.add("Matao");
        super.add("Maua");
        super.add("Mendonca");
        super.add("Meridiano");
        super.add("Mesopolis");
        super.add("Miguelopolis");
        super.add("Mineiros do Tiete");
        super.add("Mira Estrela");
        super.add("Miracatu");
        super.add("Mirandopolis");
        super.add("Mirante do Paranapanema");
        super.add("Mirassol");
        super.add("Mirassolandia");
        super.add("Mococa");
        super.add("Mogi Guacu");
        super.add("Moji das Cruzes");
        super.add("Moji-Mirim");
        super.add("Mombuca");
        super.add("Moncoes");
        super.add("Mongagua");
        super.add("Monte Alegre do Sul");
        super.add("Monte Alto");
        super.add("Monte Aprazivel");
        super.add("Monte Azul Paulista");
        super.add("Monte Castelo");
        super.add("Monte Mor");
        super.add("Monteiro Lobato");
        super.add("Morro Agudo");
        super.add("Morungaba");
        super.add("Motuca");
        super.add("Murutinga do Sul");
        super.add("Nantes");
        super.add("Narandiba");
        super.add("Natividade da Serra");
        super.add("Nazare Paulista");
        super.add("Neves Paulista");
        super.add("Nhandeara");
        super.add("Nipoa");
        super.add("Nova Alianca");
        super.add("Nova Campina");
        super.add("Nova Canaa Paulista");
        super.add("Nova Castilho");
        super.add("Nova Europa");
        super.add("Nova Granada");
        super.add("Nova Guataporanga");
        super.add("Nova Independencia");
        super.add("Nova Luzitania");
        super.add("Nova Odessa");
        super.add("Novais");
        super.add("Novo Horizonte");
        super.add("Nuporanga");
        super.add("Ocaucu");
        super.add("Oleo");
        super.add("Olimpia");
        super.add("Onda Verde");
        super.add("Oriente");
        super.add("Orindiuva");
        super.add("Orlandia");
        super.add("Osasco");
        super.add("Oscar Bressane");
        super.add("Osvaldo Cruz");
        super.add("Ourinhos");
        super.add("Ouro Verde");
        super.add("Ouroeste");
        super.add("Pacaembu");
        super.add("Palestina");
        super.add("Palmares Paulista");
        super.add("Palmeira d'Oeste");
        super.add("Palmital");
        super.add("Panorama");
        super.add("Paraguacu Paulista");
        super.add("Paraibuna");
        super.add("Paraiso");
        super.add("Paranapanema");
        super.add("Paranapua");
        super.add("Parapua");
        super.add("Pardinho");
        super.add("Pariquera-Acu");
        super.add("Parisi");
        super.add("Patrocinio Paulista");
        super.add("Pauliceia");
        super.add("Paulinia");
        super.add("Paulistania");
        super.add("Paulo de Faria");
        super.add("Pederneiras");
        super.add("Pedra Bela");
        super.add("Pedranopolis");
        super.add("Pedregulho");
        super.add("Pedreira");
        super.add("Pedrinhas Paulista");
        super.add("Pedro de Toledo");
        super.add("Penapolis");
        super.add("Pereira Barreto");
        super.add("Pereiras");
        super.add("Peruibe");
        super.add("Piacatu");
        super.add("Piedade");
        super.add("Pilar do Sul");
        super.add("Pindamonhangaba");
        super.add("Pindorama");
        super.add("Pinhalzinho");
        super.add("Piquerobi");
        super.add("Piquete");
        super.add("Piracaia");
        super.add("Piracicaba");
        super.add("Piraju");
        super.add("Pirajui");
        super.add("Pirangi");
        super.add("Pirapora do Bom Jesus");
        super.add("Pirapozinho");
        super.add("Pirassununga");
        super.add("Piratininga");
        super.add("Pitangueiras");
        super.add("Planalto");
        super.add("Platina");
        super.add("Poa");
        super.add("Poloni");
        super.add("Pompeia");
        super.add("Pongai");
        super.add("Pontal");
        super.add("Pontalinda");
        super.add("Pontes Gestal");
        super.add("Populina");
        super.add("Porangaba");
        super.add("Porto Feliz");
        super.add("Porto Ferreira");
        super.add("Potim");
        super.add("Potirendaba");
        super.add("Pracinha");
        super.add("Pradopolis");
        super.add("Praia Grande");
        super.add("Pratania");
        super.add("Presidente Alves");
        super.add("Presidente Bernardes");
        super.add("Presidente Epitacio");
        super.add("Presidente Prudente");
        super.add("Presidente Venceslau");
        super.add("Promissao");
        super.add("Quadra");
        super.add("Quata");
        super.add("Queiroz");
        super.add("Queluz");
        super.add("Quintana");
        super.add("Rafard");
        super.add("Rancharia");
        super.add("Redencao da Serra");
        super.add("Regente Feijo");
        super.add("Reginopolis");
        super.add("Registro");
        super.add("Restinga");
        super.add("Ribeira");
        super.add("Ribeirao Bonito");
        super.add("Ribeirao Branco");
        super.add("Ribeirao Corrente");
        super.add("Ribeirao Grande");
        super.add("Ribeirao Pires");
        super.add("Ribeirao Preto");
        super.add("Ribeirao do Sul");
        super.add("Ribeirao dos Indios");
        super.add("Rifaina");
        super.add("Rincao");
        super.add("Rinopolis");
        super.add("Rio Claro");
        super.add("Rio Grande da Serra");
        super.add("Rio das Pedras");
        super.add("Riolandia");
        super.add("Riversul");
        super.add("Rosana");
        super.add("Roseira");
        super.add("Rubiacea");
        super.add("Rubineia");
        super.add("Sabino");
        super.add("Sagres");
        super.add("Sales Oliveira");
        super.add("Sales");
        super.add("Salesopolis");
        super.add("Salmourao");
        super.add("Saltinho");
        super.add("Salto Grande");
        super.add("Salto de Pirapora");
        super.add("Salto");
        super.add("Sandovalina");
        super.add("Santa Adelia");
        super.add("Santa Albertina");
        super.add("Santa Barbara d'Oeste");
        super.add("Santa Branca");
        super.add("Santa Clara d'Oeste");
        super.add("Santa Cruz da Conceicao");
        super.add("Santa Cruz da Esperanca");
        super.add("Santa Cruz das Palmeiras");
        super.add("Santa Cruz do Rio Pardo");
        super.add("Santa Ernestina");
        super.add("Santa Fe do Sul");
        super.add("Santa Gertrudes");
        super.add("Santa Isabel");
        super.add("Santa Lucia");
        super.add("Santa Maria da Serra");
        super.add("Santa Mercedes");
        super.add("Santa Rita d'Oeste");
        super.add("Santa Rita do Passa Quatro");
        super.add("Santa Rosa de Viterbo");
        super.add("Santa Salete");
        super.add("Santana da Ponte Pensa");
        super.add("Santana de Parnaiba");
        super.add("Santo Anastacio");
        super.add("Santo Andre");
        super.add("Santo Antonio da Alegria");
        super.add("Santo Antonio de Posse");
        super.add("Santo Antonio do Aracangua");
        super.add("Santo Antonio do Jardim");
        super.add("Santo Antonio do Pinhal");
        super.add("Santo Expedito");
        super.add("Santopolis do Aguapei");
        super.add("Santos");
        super.add("Sao Bento do Sapucai");
        super.add("Sao Bernardo do Campo");
        super.add("Sao Caetano do Sul");
        super.add("Sao Carlos");
        super.add("Sao Francisco");
        super.add("Sao Joao da Boa Vista");
        super.add("Sao Joao das Duas Pontes");
        super.add("Sao Joao de Iracema");
        super.add("Sao Joao do Pau d'Alho");
        super.add("Sao Joaquim da Barra");
        super.add("Sao Jose da Bela Vista");
        super.add("Sao Jose do Barreiro");
        super.add("Sao Jose do Rio Pardo");
        super.add("Sao Jose do Rio Preto");
        super.add("Sao Jose dos Campos");
        super.add("Sao Lourenco da Serra");
        super.add("Sao Luis do Paraitinga");
        super.add("Sao Manuel");
        super.add("Sao Miguel Arcanjo");
        super.add("Sao Paulo");
        super.add("Sao Pedro do Turvo");
        super.add("Sao Pedro");
        super.add("Sao Roque");
        super.add("Sao Sebastiao da Grama");
        super.add("Sao Sebastiao");
        super.add("Sao Simao");
        super.add("Sao Vicente");
        super.add("Sarapui");
        super.add("Sarutaia");
        super.add("Sebastianopolis do Sul");
        super.add("Serra Azul");
        super.add("Serra Negra");
        super.add("Serrana");
        super.add("Sertaozinho");
        super.add("Sete Barras");
        super.add("Severinia");
        super.add("Silveiras");
        super.add("Socorro");
        super.add("Sorocaba");
        super.add("Sud Mennucci");
        super.add("Sumare");
        super.add("Suzanapolis");
        super.add("Suzano");
        super.add("Tabapua");
        super.add("Tabatinga");
        super.add("Taboao da Serra");
        super.add("Taciba");
        super.add("Taguai");
        super.add("Taiacu");
        super.add("Taiuva");
        super.add("Tambau");
        super.add("Tanabi");
        super.add("Tapirai");
        super.add("Tapiratiba");
        super.add("Taquaral");
        super.add("Taquaritinga");
        super.add("Taquarituba");
        super.add("Taquarivai");
        super.add("Tarabai");
        super.add("Taruma");
        super.add("Tatui");
        super.add("Taubate");
        super.add("Tejupa");
        super.add("Teodoro Sampaio");
        super.add("Terra Roxa");
        super.add("Tiete");
        super.add("Timburi");
        super.add("Torre de Pedra");
        super.add("Torrinha");
        super.add("Trabiju");
        super.add("Tremembe");
        super.add("Tres Fronteiras");
        super.add("Tuiuti");
        super.add("Tupa");
        super.add("Tupi Paulista");
        super.add("Turiuba");
        super.add("Turmalina");
        super.add("Ubarana");
        super.add("Ubatuba");
        super.add("Ubirajara");
        super.add("Uchoa");
        super.add("Uniao Paulista");
        super.add("Urania");
        super.add("Uru");
        super.add("Urupes");
        super.add("Valentim Gentil");
        super.add("Valinhos");
        super.add("Valparaiso");
        super.add("Vargem Grande Paulista");
        super.add("Vargem Grande do Sul");
        super.add("Vargem");
        super.add("Varzea Paulista");
        super.add("Vera Cruz");
        super.add("Vinhedo");
        super.add("Viradouro");
        super.add("Vista Alegre do Alto");
        super.add("Vitoria Brasil");
        super.add("Votorantim");
        super.add("Votuporanga");
        super.add("Zacarias");
        
    }

}
